[keyboard]
name = "SunoHHKB2"
product_name = "SunoHHKB2"
vendor_id = 0x1209
product_id = 0x2302
manufacturer = "RMK"
chip = "nrf52840"

[matrix]
# Row and col pins are mandatory
row_pins = ["P1_02", "P1_07", "P0_31", "P0_29","P0_02"]
col_pins = ["P1_06","P1_04","P0_11","P1_00","P0_24","P0_22","P0_20","P1_11","P1_13","P1_15","P0_17","P0_08","P0_06","P0_09","P0_10"]
# RMK uses col2row as the default matrix diode direction, if you want to use a row2col matrix, add `row2col = true`
row2col = false

[layout]
rows = 5
cols = 15
layers = 4
matrix_map = """
(0,0)    (0,1)    (0,2)    (0,3)    (0,4)    (0,5)    (0,6)    (0,7)    (0,8)    (0,9)    (0,10)    (0,11)    (0,12)    (0,13)    (0,14)
(1,0)    (1,1)    (1,2)    (1,3)    (1,4)    (1,5)    (1,6)    (1,7)    (1,8)    (1,9)    (1,10)    (1,11)    (1,12)    (1,13)
(2,0)    (2,1)    (2,2)    (2,3)    (2,4)    (2,5)    (2,6)    (2,7)    (2,8)    (2,9)    (2,10)    (2,11)              (2,13)
(3,0)             (3,2)    (3,3)    (3,4)    (3,5)    (3,6)    (3,7)    (3,8)    (3,9)    (3,10)    (3,11)    (3,12)    (3,13)
         (4,1)    (4,2)                               (4,6)                                         (4,11)    (4,12)    (4,13)
"""

[[layer]]
name = "base_layer"
keys = """
Escape    Kc1      Kc2      Kc3      Kc4      Kc5      Kc6      Kc7      Kc8      Kc9      Kc0       Minus     Equal     Grave     Backspace
LT(2, Tab) Q       W        E        R        T        Y        U        I        O        P     LeftBracket RightBracket Backslash 
LCtrl     A        S        D        F        G        H        J        K        L        Semicolon Quote               Enter 
LShift             Z        X        C        V        B        N        M        Comma    Dot       Slash     RShift    MO(1)
          LGui     LAlt                               Space                                          MO(3)     TG(2)     RCtrl
"""

[[layer]]
name = "Fn_layer"
keys = """
_        F1        F2       F3       F4       F5       F6       F7       F8       F9       F10       F11       F12       Insert    Delete
_        No        No       No       No       No       No       PageUp   Insert   No     PrintScreen UP        No        No
CapsLock AudioVolDown AudioVolUp AudioMute  No No      Home     PageDown No       No       Left      Right               _ 
_                 User0     User1    User2    No       No       End      No       No       No        Down      _        _ 
         LGui      LAlt                               Space                                          MO(3)     TG(2)     RCtrl
"""

[[layer]]
name = "Number_layer"
keys = """
_        _        _       _       _       _       _       _     KpAsterisk Kc9      Kc0       KpMinus   KpPlus    No       Backspace
_ 	     No        No       No       No       No       Kp7      Kp8      Kp9      No       No        UP        No        KpSlash 
CapsLock No        NumLock  No       No       No       Kp4      Kp5      Kp6      No       Left      Right               KpEnter
_                  No       No     Calculator No       No       Kp1      Kp2      Kp3      No        Down      RShift    MO(1) 
         LGui      LAlt                                Kp0                                           KpDot     _        No 
"""

[[layer]]
name = "Mouse_layer"
keys = """
_    MouseAccel0 MouseAccel1 MouseAccel2  No   No       No       No       No       No       No        No        No        No        Delete
_    No      MouseWheelUp       No       No       No       No       No       No       No    MouseBtn1  MouseUp  MouseBtn2    _ 
CapsLock MouseWheelLeft MouseWheelRight No No No       No       No       No       No      MouseLeft  MouseRight          _ 
_            MouseWheelDown No       No       No       No       No       No       No      No      MouseDown  RShift     MO(1) 
         LGui      LAlt                                Space                                         MO(3)     TG(2)     RCtrl
"""


[light]
capslock = { pin = "P1_01", low_active = false }
#scrolllock = { pin = "PIN_1", low_active = true }
#$numslock= { pin = "PIN_2", low_active = true }

[storage]
# Storage feature is enabled by default
# enabled = false

[ble]
enabled = true
# vddh has an internal voltage divider
battery_adc_pin = "vddh"
# Or
# battery_adc_pin = "P0_04"
# adc_divider_measured = 2000
# adc_divider_total = 2806

charge_state.pin = "P0_25"
charge_state.low_active = false
charge_led.pin = "P0_15"
charge_led.low_active = true
